### ISSUE TITLE
Audio effects

### ISSUE THREAD

**Issue by forse1337** [michmich16/Terning-Spil#9]
Sound effects on dices.
Sound effects on winning.
Sound effects on losing.

**Comment by elop123** [comment]
I created shaking effect on dices, when clicking on the buttons, the dices are shaking.

**Comment by elop123** [comment]
Vi skal have 2  forskellige issues - en til effect og en til audio

**Comment by michmich16** [comment]
Elena har ret.
Jeg skriver denne issue om.

**Comment by michmich16** [comment]
Sound effects OK
Closed
